---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: {{ .Values.name }}-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /volume1/kubernetes/pv-comfyui-0001
    server: 10.77.4.252
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-model-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: {{ .Values.name }}-model-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-model-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  nfs:
    path: /volume1/kubernetes/pv-comfyui-model-0001
    server: 10.77.4.253
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
