---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: comfyui-comfyui-helm
    meta.helm.sh/release-namespace: "comfyui"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: comfyui-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /volume1/kubernetes/pv-comfyui-0001
    server: 10.77.4.252
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: comfyui-model-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-model-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  nfs:
    path: /volume1/kubernetes/pv-comfyui-model-0001
    server: 10.77.4.253
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
