---
# Source: comfyui/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comfyui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: comfyui-comfyui-helm
    meta.helm.sh/release-namespace: "comfyui"
automountServiceAccountToken: true
